/*
* This is sample code generated by rpcgen.
* These are only templates and you can use them
* as a guideline for developing your own functions.
*/
#include "IDL.h"
float *
add_3_svc(values *argp, struct svc_req *rqstp)
{
	static float result;
	result = argp->num1 + argp->num2;
	return &result;
}
float *
sub_3_svc(values *argp, struct svc_req *rqstp)
{
	static float result;
	result = argp->num1 - argp->num2;
	return &result;
}
